### PR TITLE
delete news api

### PR DESCRIPTION
**Pull request by RayhanAnandhias**
**boleh di review**

**delete by id :**
delete | http://localhost:3000/news/delete/:id

**delete all :**
delete | http://localhost:3000/news/delete-all

### CODE REVIEW

**Review by nfadhil13 — COMMENTED** [review]
MANTAP ! KEREN SEKALI KAMU !

**Review by nadiamelyani — APPROVED** [review]
nicee 👍

**Review by adevaraz — APPROVED** [review]
nice 💯 👍

**Review by mufqiuwais — APPROVED** [review]
kamu jago

**Pull request merged**
